/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.br.sc.sisloj;

import br.senai.sc.sisloj.views.CadastroCliente;
import br.senai.sc.sisloj.views.ListagemCliente;
import br.senai.sc.sisloj.views.PainelAmarelo;
import br.senai.sc.sisloj.views.PainelRosa;
import br.senai.sc.sisloj.views.TelaInicial;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class SisLojFrame extends javax.swing.JFrame {

    /**
     * Creates new form SisLojFrame
     */
    public SisLojFrame() throws SQLException {
        initComponents();

        PainelRosa pRosa = new PainelRosa();
        PainelAmarelo pAmarelo = new PainelAmarelo();
        CadastroCliente CadastroCli = new CadastroCliente();
        TelaInicial TelaIni = new TelaInicial();
        ListagemCliente ListaCli= new ListagemCliente();

        PainelPrincipal.add(pRosa, "painelRosa");
        PainelPrincipal.add(pAmarelo, "painelAmarelo");
        PainelPrincipal.add(CadastroCli, "CadastroCliente");
        PainelPrincipal.add(TelaIni, "TelaInicial");
        PainelPrincipal.add(ListaCli, "ListaCli");

        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        barraDeMenu = new javax.swing.JMenuBar();
        MenCliente = new javax.swing.JMenu();
        CadastrarCliente = new javax.swing.JMenuItem();
        ListarCliente = new javax.swing.JMenuItem();
        MenProduto = new javax.swing.JMenu();
        CadastrarProduto = new javax.swing.JMenuItem();
        ListarProdutos = new javax.swing.JMenuItem();
        ProdutosFalta = new javax.swing.JMenuItem();
        PaineisColoridos = new javax.swing.JMenu();
        Rosa = new javax.swing.JMenuItem();
        Amarelo = new javax.swing.JMenuItem();
        BotaoTelaInicial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1368, 768));
        setSize(new java.awt.Dimension(800, 500));

        this.setExtendedState(MAXIMIZED_BOTH);
        PainelPrincipal.setAlignmentX(0.0F);
        PainelPrincipal.setAlignmentY(0.0F);
        PainelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PainelPrincipal.setName(""); // NOI18N
        PainelPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PainelPrincipalComponentAdded(evt);
            }
        });
        PainelPrincipal.setLayout(new java.awt.CardLayout());

        MenCliente.setText("Clientes");

        CadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        CadastrarCliente.setText("Cadastrar Cliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        MenCliente.add(CadastrarCliente);

        ListarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        ListarCliente.setText("Listar Clientes");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });
        MenCliente.add(ListarCliente);

        barraDeMenu.add(MenCliente);

        MenProduto.setText("Produto");

        CadastrarProduto.setText("Cadastrar Produto");
        MenProduto.add(CadastrarProduto);

        ListarProdutos.setText("Listar Produtos");
        MenProduto.add(ListarProdutos);

        ProdutosFalta.setText("Produtos em Falta");
        MenProduto.add(ProdutosFalta);

        barraDeMenu.add(MenProduto);

        PaineisColoridos.setText("Paineis Coloridos");

        Rosa.setText("Painel Rosa");
        Rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RosaActionPerformed(evt);
            }
        });
        PaineisColoridos.add(Rosa);

        Amarelo.setText("Painel Amarelo");
        Amarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmareloActionPerformed(evt);
            }
        });
        PaineisColoridos.add(Amarelo);

        barraDeMenu.add(PaineisColoridos);

        BotaoTelaInicial.setText("Tela Inicial");
        BotaoTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTelaInicialActionPerformed(evt);
            }
        });
        barraDeMenu.add(BotaoTelaInicial);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
        cl.show(PainelPrincipal, "CadastroCliente");
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void PainelPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PainelPrincipalComponentAdded
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
         cl.show(PainelPrincipal, "TelaInicial");
    }//GEN-LAST:event_PainelPrincipalComponentAdded

    private void RosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RosaActionPerformed
        CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
        cl.show(PainelPrincipal, "painelRosa");


    }//GEN-LAST:event_RosaActionPerformed

    private void AmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmareloActionPerformed
        // TODO add your handling code here:

        CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
        cl.show(PainelPrincipal, "painelAmarelo");
    }//GEN-LAST:event_AmareloActionPerformed

    private void BotaoTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTelaInicialActionPerformed
        // TODO add your handling code here:CardLayout cl = (CardLayout) PainelPrincipal.getLayout();CardLayout cl = (CardLayout) PainelPrincipal.getLayout();CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
        CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
         cl.show(PainelPrincipal, "TelaInicial");
    }//GEN-LAST:event_BotaoTelaInicialActionPerformed

    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
      
        ListagemCliente lc;
        try {
            lc = new ListagemCliente();
             PainelPrincipal.add(lc, "ListaCli");
            CardLayout cl = (CardLayout) PainelPrincipal.getLayout();
            cl.show(PainelPrincipal, "ListaCli");
        } catch (SQLException ex) {
            Logger.getLogger(SisLojFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
         
    }//GEN-LAST:event_ListarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SisLojFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SisLojFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Amarelo;
    private javax.swing.JMenu BotaoTelaInicial;
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenuItem ListarCliente;
    private javax.swing.JMenuItem ListarProdutos;
    private javax.swing.JMenu MenCliente;
    private javax.swing.JMenu MenProduto;
    private javax.swing.JMenu PaineisColoridos;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JMenuItem ProdutosFalta;
    private javax.swing.JMenuItem Rosa;
    private javax.swing.JMenuBar barraDeMenu;
    // End of variables declaration//GEN-END:variables
}
